### PR TITLE
Git ignore compiled files

### PR DESCRIPTION
**Pull request by larsgw**
Ignore compiled files in `/bin` directory.

### CODE REVIEW

**Comment by leogott** [comment]
Currently, the classes should be compiled into the `target/` subdirectory. Could you please check and confirm which directory is created when you compile the project?

**Comment by larsgw** [comment]
Superseded by #51 AFAICT

**Comment by larsgw** [comment]
Sorry for dropping the ball on this, I was running an older version of CoNLL-RDF I think, and hadn't gotten around to upgrading yet.

**Comment by leogott** [comment]
Thank you for confirming, and for bringing that up in the first place!
Having a version-controlled gitignore file is always a good idea.

**Pull request closed without merging**
